### ISSUE TITLE
CKAN integration

### ISSUE THREAD

**Issue by mheguy** [magico13/MagiCore#1]
CKAN has an awkward time installing MagiCore. Because of the methods we use to install mods we can target a directory to install or individual files but we can't take, for example, all the files in a directory and move them into another directory.

So currently our 2 options are to target each file individually (in which case if you add a file in a new version we won't be installing it unless someone makes us aware of the new file) or we target the `GameData` directory and install that into `GameData` which puts your files into `GameData/GameData`.

Neither solution is ideal, so I was wondering if in future releases you could have the same archive structure as your other mods (ex. `GameData/MagiCore/`).

**Comment by magico13** [comment]
Hmm, it's a bit annoying but I can switch to putting it in a MagiCore folder. Because it's a shared set of code that I will be using in many of my mods I wanted it to have a more central location and also wanted to ensure it would be loaded first, hence keeping it in directly in GameData, but I can work around those issues if they arise and put it instead in GameData/MagiCore.

I'm guessing you all would prefer this to be done prior to getting the 1.1.2 version on CKAN? In which case you'll have to wait until I get home from work. I need to update the netkan file anyway to use the version file that I added since I first made the netkan file.

**Comment by mheguy** [comment]
https://github.com/KSP-CKAN/NetKAN/pull/3911 will make use of the version file and will change the install we perform from installing to `GameData/GameData` to just the base `GameData` folder.

https://github.com/KSP-CKAN/NetKAN/commit/db337a78a30f6caf7c587f486f4a2d06acec4f27#diff-0cad94d42ce0f1043f2aa5ea8b01f193 originally set the netkan up to install to `GameData/GameData` and (presumably/hopefully) that hasn't caused any issues to your users.

**Comment by magico13** [comment]
FYI, I've changed MagiCore in the latest update to be located within GameData/MagiCore per this request. Should I update the netkan myself or will you guys handle it? I'm going to close this issue on this side, however.

**Comment by mheguy** [comment]
https://github.com/KSP-CKAN/NetKAN/pull/4377 will have things line up on CKAN's side of things.
